import os
import sys
import pyghidra

pyghidra.start()


PROJECT_DIR = '/tmp/ghidra-export-cli'
PROJECT_NAME = 'ghidra_export'
FUNCTION_FILTER = {'register_tm_clones', 'deregister_tm_clones'}
GLOBAL_VARS_FILTER = {'stdin', 'stderr', 'stdout'}

DECOMPILED_HEADER = """/*
 Decompilation generated by Ghidra (headless)
 Program: {}
*/"""
DECOMPILED_GLOBALS_HEADER = "/* ======== Global Variables ======== */"
DECOMPILED_FUNCTION_HEADER = "/* ===== Function: {} @ {} ===== */\n"


class GhidraExport:
    def __init__(self, project, bin_path: str):
        from ghidra.program.model.symbol import SourceType
        from ghidra.app.decompiler import DecompInterface
        from ghidra.util.task import ConsoleTaskMonitor

        self.project = project
        self.program = self._load_program(bin_path)

        self.ifc = DecompInterface()
        self.ifc.openProgram(self.program)
        self.monitor = ConsoleTaskMonitor()

    def _load_program(self, bin_path):
        # TODO: move outside of class and remove bin_path param (just pass in program itself)
        load_results = pyghidra.program_loader().project(self.project).source(bin_path).name("bin").load()
        program = load_results.getPrimaryDomainObject()
        pyghidra.analyze(program)
        return program

    def get_functions(self, include_thunk=False):
        user_funcs = []
        for func in self.program.getFunctionManager().getFunctions(True):
            fname = func.getName()
            if include_thunk or (not func.isThunk() and fname[0] != '_' and fname not in FUNCTION_FILTER):
                user_funcs.append(func)
        return user_funcs

    def decompile_func(self, f) -> (str, dict[str, "HighSymbol"]):
        from ghidra.program.model.symbol import SymbolType

        global_variables = {}

        source = DECOMPILED_FUNCTION_HEADER.format(f.getName(), f.getEntryPoint())
        try:
            res = self.ifc.decompileFunction(f, 0, self.monitor)
            body = res.getDecompiledFunction().getC().strip()
            source = f'{source}{body}'


            hf = res.getHighFunction()
            for high_sym in hf.getGlobalSymbolMap().getSymbols():
                hname = high_sym.getName()
                if high_sym.getSymbol().getSymbolType() == SymbolType.LABEL and not hname.startswith('PTR_') and hname not in GLOBAL_VARS_FILTER:
                    global_variables[hname] = high_sym
        except Exception as e:
            # TODO: print error log
            source = f"{source}/* Error decompiling {f.getName()}: {e} */"

        return (source, global_variables)

    def decompile(self, include_thunk=False):
        funcs = self.get_functions(include_thunk)

        decompiled_source = []
        global_variables = {}

        for f in sorted(funcs, key=lambda x: x.getEntryPoint()):
            source, gvars = self.decompile_func(f)
            global_variables.update(gvars)
            decompiled_source.append(source)

        symbol_man = self.program.getSymbolTable()
        globals_source = [DECOMPILED_GLOBALS_HEADER]
        for name, high_sym in global_variables.items():
            # For some reason, high_sym.getSymbol().getAddress() sometimes fails to get accurate address
            addr = symbol_man.getGlobalSymbols(name)[0].getAddress()
            globals_source.append(f'/* {high_sym.getDataType()} {name} @ {addr} */')

        source_components = [
            DECOMPILED_HEADER.format(self.program.name),
            '\n'.join(globals_source),
            '\n\n\n'.join(decompiled_source)
        ]

        return '\n\n\n'.join(source_components)



def main():
    from ghidra.base.project import GhidraProject
    # TODO: check args

    bin_path = os.path.abspath(sys.argv[1])
    out_path = os.path.abspath("./decompiled")

    print("Decompiling...")
    try:
        os.makedirs(PROJECT_DIR, exist_ok=True)
    except OSError as e:
        print(f'Error making project directory: {e}')
        exit(1)

    with pyghidra.open_project(PROJECT_DIR, PROJECT_NAME, create=True) as project:
        ghidra_export = GhidraExport(project, bin_path)
        with open(out_path, "w") as f:
            f.write(ghidra_export.decompile())

    print("Finished decompiling.")


if __name__ == "__main__":
    main()

